import { AppProviders } from '@/providers/AppProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medistore',
  description: 'Generated by hxn203',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <AppProviders>
            {children}
          </AppProviders>
      </body>
    </html>
  )
}
