import { AppProviders } from '@/providers/appProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medicare',
  description: 'Generated by hxn203',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          <Header />
          {children}
        </AppProviders>
      </body>
    </html>
  )
}
