version: '3.8'

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
      tag: "{{.Name}}"
      mode: "non-blocking"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://tracking-api:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - NEXT_WEBPACK_USEPOLLING=1
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - tracking-api
    <<: *default-logging
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  tracking-api:
    build: 
      context: ./tracking-api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/KLTN_2025
      - MONGODB_DB_NAME=KLTN_2025
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - RELOAD=true
      - DEBUG=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    volumes:
      - ./tracking-api:/app:delegated
      - tracking_api_cache:/app/__pycache__
    depends_on:
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    <<: *default-logging
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  consumer:
    build: 
      context: ./consumer
      dockerfile: Dockerfile.dev
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/KLTN_2025
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - AIR_FORCE_BUILD=true
    volumes:
      - ./consumer:/app:delegated
      - consumer_go_cache:/go/pkg/mod
      - consumer_air_tmp:/app/tmp
    depends_on:
      - rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    <<: *default-logging
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3
    <<: *default-logging
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  rabbitmq_data:
  frontend_node_modules:
  frontend_next:
  tracking_api_cache:
  consumer_go_cache:
  consumer_air_tmp:
