version: '3.8'

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3000:3000"
    restart: always

  tracking-api:
    image: ${TRACKING_API_IMAGE}
    ports:
      - "8000:80"
    restart: always
