version: '3.8'

services:
  vault:
    image: vault:1.13.3
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_UI=true
    volumes:
      - ./vault/config:/vault/config:ro
      - ./vault/data:/vault/data
    command: server -config=/vault/config/vault.json

  vault-init:
    image: vault:1.13.3
    depends_on:
      - vault
    volumes:
      - ./vault/init:/scripts
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=myroot
    command: sh /scripts/init.sh

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      ${FRONTEND_ENV}
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    depends_on:
      - vault-init
      - tracking-api

  tracking-api:
    build: 
      context: ./tracking-api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      ${API_ENV}
    volumes:
      - ./tracking-api:/app:delegated
      - tracking_api_cache:/app/__pycache__
    depends_on:
      - vault-init
      - mongodb
      - redis
      - rabbitmq

  consumer:
    build: 
      context: ./consumer
      dockerfile: Dockerfile.dev
    environment:
      ${CONSUMER_ENV}
    volumes:
      - ./consumer:/app:delegated
      - consumer_go_cache:/go/pkg/mod
      - consumer_air_tmp:/app/tmp
    depends_on:
      - vault-init
      - mongodb
      - redis
      - rabbitmq

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:
  frontend_node_modules:
  frontend_next:
  tracking_api_cache:
  consumer_go_cache:
  consumer_air_tmp:
