FROM golang:1.21-alpine as builder

WORKDIR /app
COPY go.mod go.sum ./

RUN apk add --no-cache git \
    && go install github.com/cosmtrek/air@v1.44.0

FROM golang:1.21-alpine
WORKDIR /app

RUN apk add --no-cache git

COPY --from=builder /go/bin/air /go/bin/air
COPY . .

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
