pipeline {
    agent any

    tools {
        nodejs 'Node20'
    }

    environment {
        DOCKER_REGISTRY = "medicare_frontend"  // Replace with your Docker registry
        DOCKER_IMAGE = "frontend"
        IMAGE_TAG = "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'hxn203',
                    url: 'git@github.com:dxnghxn203/KLTN_2025.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    script {
                        def packageChanged = sh(script: 'git diff --name-only HEAD~1 HEAD | grep "frontend/package.json" || true', returnStatus: true) == 0
                        def yarnLockChanged = sh(script: 'git diff --name-only HEAD~1 HEAD | grep "frontend/yarn.lock" || true', returnStatus: true) == 0
                        if (packageChanged || yarnLockChanged) {
                            sh 'yarn install --frozen-lockfile'
                        } else {
                            echo 'No changes in package.json or yarn.lock, skipping yarn install'
                        }
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'yarn build'
                    script {
                        sh "docker build -t ${IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    docker.withRegistry("", "dockerhub-id") {
                        sh "docker push ${IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Deploy') {
            when { branch 'main' }
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ec2-user@46.137.203.192 '\
                            cd ~/app && \
                            docker-compose stop frontend && \
                            docker-compose rm -f frontend && \
                            echo "FRONTEND_IMAGE=${IMAGE_TAG}" > .env && \
                            docker-compose up -d frontend'
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
