version: '3.8'

services:
  # rabbitmq:
  #   build:
  #     context: .
  #     dockerfile: ./rabbitmq/Dockerfile
  #   container_name: tracking-rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=kltn_2025
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 200M
  #         cpus: '0.3'
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "rabbitmqctl", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: tracking-elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms64m -Xmx64m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '0.3'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  # rabbitmq-data:
  #   driver: local
  elasticsearch-data:
    driver: local
