version: '3.8'

services:
  rabbitmq:
    build:
      context: .  # Thay đổi context lên một cấp để bao gồm thư mục rabbitmq
      dockerfile: ./rabbitmq/Dockerfile
    container_name: tracking-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=kltn_2025
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '0.2'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  rabbitmq-data:
    driver: local
