name: Build Tracking API (Test)

on:
  push:
    paths:
      - '.github/workflows/build-tracking-api.yml'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/tracking-api-kltn2025
  API_DIR: ./tracking-manager/packages/tracking-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Secrets from Vault
        id: vault-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            MONGO_HOST=production/.env MONGO_HOST
            RABBITMQ_USER=production/.env RABBITMQ_USER
            RABBITMQ_PW=production/.env RABBITMQ_PW
            RABBITMQ_HOST=production/.env RABBITMQ_HOST
            RABBITMQ_PORT=production/.env RABBITMQ_PORT
            RABBITMQ_VHOST=production/.env RABBITMQ_VHOST
            REDIS_HOST=production/.env REDIS_HOST
            REDIS_PORT=production/.env REDIS_PORT
            REDIS_PASSWORD=production/.env REDIS_PASSWORD
            SUPABASE_PASS=production/.env SUPABASE_PASS
            SUPABASE_key=production/.env SUPABASE_key
            SUPABSE_URL=production/.env SUPABSE_URL
            API_MONGO_USER=production/.env API_MONGO_USER
            API_MONGO_PWS=production/.env API_MONGO_PWS
            API_MONGO_DB=production/.env API_MONGO_DB
            ES_HOST=production/.env ES_HOST
            ES_PORT=production/.env ES_PORT
            ES_USER=production/.env ES_USER
            ES_PW=production/.env ES_PW
            PAYMENT_API_URL=production/.env PAYMENT_API_URL
            GMAIL_PASS=production/.env GMAIL_PASS
            GMAIL_USER=production/.env GMAIL_USER
            JWT_PRIVATE_KEY=production/.env JWT_PRIVATE_KEY
            JWT_PUBLIC_KEY=production/.env JWT_PUBLIC_KEY
            ALGORITHM=production/.env ALGORITHM
            API_PORT=production/.env API_PORT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.API_DIR }}
          file: ${{ env.API_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            MONGO_HOST=${{ env.MONGO_HOST }}
            RABBITMQ_USER=${{ env.RABBITMQ_USER }}
            RABBITMQ_PW=${{ env.RABBITMQ_PW }}
            RABBITMQ_HOST=${{ env.RABBITMQ_HOST }}
            RABBITMQ_PORT=${{ env.RABBITMQ_PORT }}
            RABBITMQ_VHOST=${{ env.RABBITMQ_VHOST }}
            REDIS_HOST=${{ env.REDIS_HOST }}
            REDIS_PORT=${{ env.REDIS_PORT }}
            REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            SUPABASE_PASS=${{ env.SUPABASE_PASS }}
            SUPABASE_key=${{ env.SUPABASE_key }}
            SUPABSE_URL=${{ env.SUPABSE_URL }}
            API_MONGO_USER=${{ env.API_MONGO_USER }}
            API_MONGO_PWS=${{ env.API_MONGO_PWS }}
            API_MONGO_DB=${{ env.API_MONGO_DB }}
            ES_HOST=${{ env.ES_HOST }}
            ES_PORT=${{ env.ES_PORT }}
            ES_USER=${{ env.ES_USER }}
            ES_PW=${{ env.ES_PW }}
            PAYMENT_API_URL=${{ env.PAYMENT_API_URL }}
            GMAIL_PASS=${{ env.GMAIL_PASS }}
            GMAIL_USER=${{ env.GMAIL_USER }}
            JWT_PRIVATE_KEY=${{ env.JWT_PRIVATE_KEY }}
            JWT_PUBLIC_KEY=${{ env.JWT_PUBLIC_KEY }}
            ALGORITHM=${{ env.ALGORITHM }}
            API_PORT=${{ env.API_PORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max