name: Build Tracking API (Test)

on:
  push:
    paths:
      - '.github/workflows/build-tracking-api.yml'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/tracking-api-kltn2025
  API_DIR: ./tracking-manager/packages/tracking-api
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Vault Secrets as JSON
        id: vault-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ env.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false
          secrets: |
            secret/production .env | ENV_FILE_JSON

      - name: Create .env file
        run: |
          echo '${{ steps.vault-secrets.outputs.ENV_FILE_JSON }}' > ${{ env.API_DIR }}/.env
          echo "Created .env file from Vault JSON data"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.API_DIR }}
          file: ${{ env.API_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-files: |
            "ENV_FILE=${{ env.API_DIR }}/.env"