name: Build Frontend KLTN2025

on:
  push:
    branches: [ main ]
    paths:
      - 'front-end/**'
      - '.github/workflows/build-frontend-nextjs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'front-end/**'
      - '.github/workflows/build-frontend-nextjs.yml'

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v20 with Yarn Cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: front-end/yarn.lock

      - name: Import Frontend Secrets from Vault
        id: vault-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: secret/production/.env * | ;

      - name: Install Dependencies (using cache)
        run: yarn install --frozen-lockfile

      - name: Build Next.js Application
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            front-end/.next
            front-end/package.json
            front-end/yarn.lock 
            # front-end/public
          retention-days: 5 